language: node_js
node_js:
- '11'
cache:
  directories: node_modules
before_script:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: WoXeG/g5FzLy96oB/xkAIHdTe+CU7WB56iTjrbdSaRoedTl4KJv+BHb1UXcEHxqMLAdkci9DrZfxSct1EgDYkKf12yc2FFnKuVFOdC6Z8Qr2r/IbH8g9/0rjB6LE4AZtyEVCIz60e9Fw8ClLgt4Um250IWv0BnBBjQ4VXBjA/1/WS4D/M1/7wduGJTmDbWuculU35Y6a0rsOyY36FqshObCp29HBc7Fadv1A50TMaFmvbuG4QDR7F0A73dDPmG1NDQAqTzPQBrT4kkhDnnrR6Qdhh10FYfr9Dr2H22nBzEipXpFaIs4KWzZDtAYwRQD59skW+/nNEF3uRttxFGX2ET+BhmdFpK+1mu8LhRCgwaExONCzIPSCYMVZqD9wlzmS8no2riSCeg185VkcXIwx3VSqlnIov3ZuRfs8xCqU9F6hj/nJmJ3stG3dLCDTyylKFUlVo/+rlT5dNG171GDIVm22rYx67yqazX7bs+dFKWMNqslvG9mxc9M+oguDMgn5lugcxXCcIboyyQzG+0gSu1LPDh+whwQoKFQf3PrGXkH3DPWDNGIMpP4WUqXBbSyFY4zX8imrNRxB4gSGJxY2LgAJIcWkHewVoVN3R0h8sO7rFda5EFDPZraBblq6bEj1Sme2HkfhlQzgc2BUOMQQ8KkVX+subXr0m6qo8VOsSOU=
  app: react-pokedex
  on:
    repo: wellitongervickas/react-pokedex
