language: node_js

node_js:
- '11'
cache:
  directories: node_modules

before_script:
  - npm install

script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: RdGAxn6Y8PJ10RtzR6p+vzMCNMq/uf6KYwiF+ziaE9J3FOc1LIq4bSPaVw4UbSlv/8sG25KAON9F5babeABkaCSGsg7/ND8IaQ5OmqJObZfQsAOh2MpnzviMkIt7M857A7YcNkQFQedtGahu+TG84wlLk+REzWHFAlRqecGRkcoTY2/3udFgikZRR17GXMIqv3phJVMKUJ837ID/0NQRS9gZmf+Fx6oWUXoFi+so9GMarAi+2UB8h10YuNYkjeBNl//AOH+RiD6yz/VEl2QlCaGGMupa7Xhl8KIENhGpNix7OEEBHRIBCaDbZ5T0jUCgTs+bFkV8vEGvtKHYXwDs0JYY8Ig2vNV8hPQYAet/mO+YlZ9YFWbBgSrqoaveONMyc1ZGfNIz4K++GFDPQMxuCnrvD8FEtCdtfvbILU8y0B0X4neRjU0PNJ3856oEPXW9bEIwXsgxY4KrEufaA7ObjSWugt+uukO25q4q81yrLL6oR6t5yjpcw/09v9nmawHt5GLmqO5IHFNDHJN8yUgdWoYpAHBxpBuPmDA4ORokb+QkmUoIcKdYST6BXoXsWXyfjBSUK6xZYi3Elu+6GlmIsu5pfISNfpWkiZy6qCpdH1oQRRVJWI6QD/UHdoPHBgb35Vr9ogAWHJ+zeP/8/EjAaCM+ubg4wYzsdxMFPWPKxNk=
  app: react-pokedex
  on:
    repo: wellitongervickas/react-pokedex